version: '3.8'

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data-volume-postgres:/var/lib/postgresql/data

volumes:
  data-volume-postgres:
